name: "Deploy"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed

env:
  PROJECT: api
  STATEBUCKET: littleurl-terraform-state
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  TF_VAR_aws_accounts: ${{ secrets.TF_VAR_AWS_ACCOUNTS }}

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.17.7"

      - name: Install dependencies
        run: go mod tidy

      - name: Build functions
        run: make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/
          retention-days: 5

  dev-terraform:
    name: "Deploy Dev Terraform"
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    # Use the Bash shell and set working dir
    defaults:
      run:
        shell: bash
        working-directory: infrastructure/

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.5

      # Initialize terraform and select workspace.
      - name: Init Terraform
        run: |
          terraform init -backend-config "role_arn=${{ secrets.TF_BACKEND_ROLE_ARN }}"
          terraform workspace select dev

      # Auto apply
      - name: Auto apply
        if: ${{ github.event_name == 'push' }}
        run: terraform apply -auto-approve

      # Download plan
      - name: Download plan
        uses: keithweaver/aws-s3-github-action@v1.0.0
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == 'true' }}
        with:
          source: s3://$STATEBUCKET/dev/$PROJECT/${{ github.event.number }}.tfplan
          destination: ./dev.tfplan
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Apply plan
      - name: Apply plan
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == 'true' }}
        run: terraform apply -auto-approve ./dev.tfplan

  dev-functions:
    name: "Deploy Dev Functions"
    runs-on: ubuntu-latest
    environment: dev
    needs: [build]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/

      - name: Upload functions
        run: |
          cd build/functions && for i in *; do \
            aws s3 cp $i s3://${{ secrets.FUNCTIONS_BUCKET }}/$i && \
            aws lambda update-function-code --function-name littleurl-${i:0:-4} --s3-bucket ${{ secrets.FUNCTIONS_BUCKET }} --s3-key $i \
          ; done


  prod-terraform:
    name: "Deploy Prod Terraform"
    runs-on: ubuntu-latest
    environment: prod

    # enforce dev-first and PR only deployments
    needs: [dev-terraform]
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == 'true' }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    # Use the Bash shell and set working dir
    defaults:
      run:
        shell: bash
        working-directory: infrastructure/

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.5

      # Initialize terraform and select workspace.
      - name: Init Terraform
        run: |
          terraform init -backend-config "role_arn=${{ secrets.TF_BACKEND_ROLE_ARN }}"
          terraform workspace select prod

      # Download plan
      - name: Download plan
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          source: s3://$STATEBUCKET/prod/$PROJECT/${{ github.event.number }}.tfplan
          destination: ./prod.tfplan
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Apply plan
      - name: Apply Plan
        run: terraform apply -auto-approve prod.tfplan

  prod-functions:
    name: "Deploy Prod Functions"
    runs-on: ubuntu-latest
    environment: prod
    needs: [build, dev-functions]
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == 'true' }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/

      - name: Upload functions
        run: |
          cd build/functions && for i in *; do \
            aws s3 cp $i s3://${{ secrets.FUNCTIONS_BUCKET }}/$i && \
            aws lambda update-function-code --function-name littleurl-${i:0:-4} --s3-bucket ${{ secrets.FUNCTIONS_BUCKET }} --s3-key $i \\
          ; done
